config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}


  root to: 'tweets#feed'

  resources :users, only: [:show, :update]

  resources :tweets, only: [:create, :index]

  get 'tweets/feed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  before_save :default_values


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # attr_accessor :email, :password, :username, :avatar, :avatar_cache, :remove_avatar, :following_users

  # validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  has_many :tweets, dependent: :destroy
  validates :username, presence: true, uniqueness: true

  def default_values
    self.following_users ||= "[]"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  #setting this up to allow updating users' attribute
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :username, :following_users, :avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password, :following_users, :avatar, :avatar_cache])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    # raise
    super
  end

  protected

  def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params["password"]&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end
end

app/controllers/tweets_controller.rb
require 'json'

class TweetsController < ApplicationController
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    respond_to do |format|
      format.json do
        if @tweet.save!
          render :json => @tweet.to_json(include: :user)
        else
          render :json => { :errors => @tweet.errors.messages }
        end
      end
    end
  end

  def index
    @tweets = Tweet.all.order(updated_at: :desc)
    @users_array = []
    @users_array = JSON.parse(current_user.following_users) if current_user.following_users != nil

    respond_to do |format|
      format.html
      format.json { render :json => @tweets.to_json(include: :user) }
    end
  end

  def feed
    following_tweets = []
    @users_array = []
    if current_user != nil && current_user.following_users != nil
      @users_array = JSON.parse(current_user.following_users)
      @users_array.each do |user_id|
        user_obj = User.find(user_id)
        following_tweets += user_obj.tweets
      end
      sorted_tweets = following_tweets.sort_by{|x|x.updated_at}.reverse
    end

    respond_to do |format|
      format.html
      format.json { render :json => sorted_tweets.to_json(include: :user) }
    end

  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
require 'json'
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user:params[:id]).order(updated_at: :desc)
    respond_to do |format|
      format.html
      format.json { render :json => @tweets.to_json(include: :user) }
    end
  end

  def update
    @user = current_user
    users_array = user_params[:following_users].split(",").map {|i|i.to_i}.to_s
    @user.following_users = users_array
    @user.save!
  end

  private

  def user_params
    params.require(:user).permit(:following_users, :password, :email, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Feed page", tweets_feed_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "General page", tweets_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "profile.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
<!--   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/tweets/create.js.erb
function refreshForm(innerHTML) {
  const newTweetForm = document.getElementById('new_tweet');
  newTweetForm.innerHTML = innerHTML;
}

function addTweet(tweetHTML) {
  const tweets = document.getElementById('tweets');
  tweets.insertAdjacentHTML('beforebegin', tweetHTML);
}

<% if @tweet.errors.any? %>
  refreshForm('<%= j render "tweets/form", user: current_user, tweet: @tweet %>');
<% else %>
  addTweet('<%= j render "tweets/show", tweet: @tweet %>');
  refreshForm('<%= j render "tweets/form", user: current_user, tweet: Tweet.new %>');
<% end %>

app/views/tweets/feed.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div id="feeds" class="feeds-list">
        <h3 class="text-center">Welcome</h3>
        <h4> Tweet now! <i>(up to 140 characters)</i></h4>
        <div style="display: flex; flex-direction: column;">
          <textarea name="Text1" cols="40" rows="5" class="form-control content" v-model="tweet.content" placeholder="Write your tweet here" ></textarea>
          <span style="color:red">{{ errors.content }}</span>
          <div class="button" style="display:flex">
            <button class="btn btn-primary tweet-btn"  @click="saveTweet">Submit</button>
            <!-- <div id="characters" class="text-center" style="margin: auto 2px"><i>0</i></div> -->
          </div>
        </div>
        <ul class="list-group" v-for="tweet in tweets" style="margin-top: 20px">
          <li class="list-group-item tweet-row" style="display: flex">
            <div style="display: flex; align-items: center; justify-content: center;   flex-direction: column;">
              <a class="img-thumbnail" v-bind:href="'/users/'+ tweet.user.id"> <%= image_tag("user-default.png", height: '64', width: '64')%> </a>
              <a v-bind:href="'/users/'+ tweet.user.id" class="text-center" style="width: 120px"> {{ tweet.user.username }} </a>
            </div>
            <div style="margin: auto 20px;"> {{ tweet.content }} </div>
          </li>
        </ul>
        <div id="users_array" style="display: none;"> <%= @users_array %> </div>
        <div id="current_user" style="display: none;"> <%= current_user.id %> </div>
      </div>
    </div>
  </div>
</div>

    <%= javascript_pack_tag 'feed' %>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <h2>What are people tweeting now</h1>

      <div id="tweets">
        <div style="display: flex; flex-direction: column;">
          <textarea name="Text1" cols="40" rows="5" class="form-control" v-model="tweet.content" placeholder="Write your tweet here" ></textarea>
          <span style="color:red">{{ errors.content }}</span>
          <div class="button" style="display:flex">
            <button class="btn btn-primary tweet-btn"  @click="saveTweet">Submit</button>
            <!-- <div id="characters" class="text-center" style="margin: auto 2px"><i>0</i></div> -->
          </div>
        </div>
        <ul class="list-group" v-for="tweet in tweets" style="margin-top: 20px">
          <li class="list-group-item tweet-row" style="display: flex; justify-content: space-between;">
            <div style="display: flex; align-items: center; justify-content: center;   flex-direction: column;">
              <a class="img-thumbnail" v-bind:href="'/users/'+ tweet.user.id"> <%= image_tag("user-default.png", height: '64', width: '64')%> </a>
              <a v-bind:href="'/users/'+ tweet.user.id" class="text-center" style="width: 120px">{{ tweet.user.username }} </a>
            </div>
            <div style="margin: auto 10px; align-content: left; width: 58%;"> {{ tweet.content }} </div>
            <div style="margin: auto 0px; align-content: right; width: 70px;"> {{ tweet.follow}} </div>
          </li>
        </ul>
        <div id="users_array" style="display: none;"> <%= @users_array %> </div>
      </div>

  </div>
  </div>
</div>


    <%= javascript_pack_tag 'index' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div id="show" class="tweet-list">
        <h3 class="text-center"> <%= @user.username %> 's Tweets</h3>
        <button class="btn btn-primary follow-btn text-center" style="margin: auto;" @click="follow"> click to follow/unfollow </button>
        <ul class="list-group" v-for="tweet in tweets" style="margin-top: 20px">
          <li class="list-group-item tweet-row">{{ tweet.content }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id = "select-id" style="display: none"> <%= params[:id] %> </div>
<div id = "current-user-id" style="display: none"> <%= current_user.id %> </div>
<div id="following_users" style="display: none;"> <%= current_user.following_users %> </div>


    <%= javascript_pack_tag 'show' %>